spring.application.name=bookhub-api

# infos BDD
spring.datasource.url=jdbc:sqlserver://localhost;databasename=BookHub;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=bookhub_admin
spring.datasource.password=BookHub2026!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

# JWT
app.jwt.secret = 393a3b433f732725296e2b56397133307839403923456a34433e57794a6f2b63